<a href="https://colab.research.google.com/github/AkshatRai3/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

In [6]:
# creating a 1D array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
# creating a 2D array
b = np.array([[1.2,2.3,3.4],[4.5,5.6,6.7]])
print(b)


[[1.2 2.3 3.4]
 [4.5 5.6 6.7]]


In [9]:
#Get dimensions of array
print(a.ndim)
print(b.ndim)

1
2


In [10]:
#Get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [11]:
#Get type
print(a.dtype)
print(b.dtype)

int64
float64


In [12]:
#Get size
print(a.itemsize)
print(b.itemsize)

8
8


In [13]:
#Get total size
print(a.nbytes)
print(b.nbytes)

24
48


In [15]:
#Get a specific element
b[1,2]

np.float64(6.7)

In [16]:
#Get a specific row
b[1,:]

array([4.5, 5.6, 6.7])

In [19]:
#Get a specific column
b[:, 1]

array([2.3, 5.6])

In [34]:
#3D array
c = np.array([[[1,2],[2,3],[3,4]],[[4,5],[5,6],[6,7]]])
print(c)

[[[1 2]
  [2 3]
  [3 4]]

 [[4 5]
  [5 6]
  [6 7]]]


In [35]:
c.itemsize

8

In [36]:
c.nbytes

96

In [37]:
c.shape

(2, 3, 2)

**Initialising different types of arrays**

In [48]:
#All zeros
np.zeros((2,3,4), dtype = "int32")

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int32)

In [54]:
#All ones matrix
np.ones((4,2,2),dtype="int64")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [55]:
#Matrix with all elements same: np.full((shape),number)
np.full((2,3,1), 13)

array([[[13],
        [13],
        [13]],

       [[13],
        [13],
        [13]]])

In [57]:
#To make a new array with same elements but similar to a previously built element
np.full_like(c,3)

array([[[3, 3],
        [3, 3],
        [3, 3]],

       [[3, 3],
        [3, 3],
        [3, 3]]])

In [104]:
#Random decimal numbers array
print(np.full((2,3),np.random.randint(6,69)))
print(np.random.rand(2,5))
print(np.random.randint(3,5, size=(3,7,1)))

[[66 66 66]
 [66 66 66]]
[[0.59796902 0.73817113 0.06397086 0.36094712 0.98240674]
 [0.11423815 0.00505704 0.24178221 0.94478382 0.09029583]]
[[[3]
  [3]
  [3]
  [3]
  [4]
  [4]
  [4]]

 [[4]
  [4]
  [4]
  [3]
  [3]
  [4]
  [3]]

 [[3]
  [3]
  [4]
  [3]
  [3]
  [3]
  [3]]]


In [105]:
#Identitiy matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [112]:
#Repeating an array
arr = np.array([[1,2,3], [4,5,6]])
r1 = np.repeat(arr,4, axis = 1)
print(r1)

[[1 1 1 1 2 2 2 2 3 3 3 3]
 [4 4 4 4 5 5 5 5 6 6 6 6]]
