<a href="https://colab.research.google.com/github/AkshatRai3/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [8]:
# creating a 1D array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [9]:
# creating a 2D array
b = np.array([[1.2,2.3,3.4],[4.5,5.6,6.7]])
print(b)


[[1.2 2.3 3.4]
 [4.5 5.6 6.7]]


In [11]:
#Get dimensions of array
print(a.ndim)
print(b.ndim)

1
2
